import type {
  AgentResponse,
  MemoryEntryResponse,
  MemoryJobView,
  MemorySessionOption,
  MemorySummary,
  MemoryTurnRow,
  PersonaResponse,
  PolicyView,
  RuntimeConfig,
  SessionResponse,
} from "../../shared/contracts";
import type { BrowserStateStorage } from "../browser-state";
import type {
  AgentDraft,
  ChatItem,
  LoadStatus,
  Page,
  PendingNavigation,
  SectionKey,
  SettingsView,
} from "./types";

export const initial = {
  status: "idle" as LoadStatus,
  error: null as string | null,
  feedback: "",
  page: "chat" as Page,
  settingsView: "hub" as SettingsView,
  activeSection: "A" as SectionKey,
  detailOpen: false,
  dirty: false,
  pendingNavigation: null as PendingNavigation | null,
  navigationConfirmOpen: false,
  navigationConfirmMessage: "",
  agents: [] as AgentResponse[],
  sessions: [] as SessionResponse[],
  messages: [] as ChatItem[],
  runtimeConfig: null as RuntimeConfig | null,
  runtimeConfigUnavailable: false,
  selectedNewSessionAgentId: null as string | null,
  currentSessionId: null as string | null,
  editorAgentId: "__new__" as const,
  editorDraft: null as AgentDraft | null,
  persona: null as PersonaResponse | null,
  policy: null as PolicyView | null,
  memorySessions: [] as MemorySessionOption[],
  memoryTurns: [] as MemoryTurnRow[],
  memoryEntries: [] as MemorySummary[],
  memoryEntryTotal: 0,
  memoryEntryDetail: null as MemoryEntryResponse | null,
  memoryJobs: [] as MemoryJobView[],
  modelNames: [] as string[],
  modelStatus: "模型列表将在打开配置时加载。",
  capacityPreview: "",
  chatContextCapacity: null as number | null,
  composer: "",
  sending: false,
  pendingOperations: 0,
  browserStateStorage: null as BrowserStateStorage | null,
};
