-- 主动开口门槛（用户 2026-09-25 弹窗定下：判断从"说/不说"改成打分）。
--
-- 判断模型此前只回一个布尔值（speak），"她多主动"只能靠判断提示词的措辞去调，没有数字可拧。
-- 现在判断回答是 0–10 的兴趣分，这一列是门槛：分数 ≥ 门槛才允许开口。
--
--   0  = 只要能读出一个分数就开口（最吵；不是"关掉判断"）
--   10 = 几乎不开口
--   默认 6 … 接近原来的行为（模型说"值得说"的那类消息通常 7 分以上），但整体略安静。
--
-- 只作用于两条主动路径（自主接话 chiming_in / 冷场发起 idle_topic）——它们共用同一次判断，
-- 所以共用同一个门槛；直接回应、连续交谈与被回复不经过判断，不受这一列影响。
ALTER TABLE qq_schemes ADD COLUMN initiative_min_score INTEGER NOT NULL DEFAULT 6 CHECK (initiative_min_score >= 0 AND initiative_min_score <= 10);
