-- 历史行保持 NULL＝原因未知。
ALTER TABLE outbound_intents ADD COLUMN stale_reason TEXT CHECK (stale_reason IS NULL OR stale_reason IN ('DELIVERY_TTL_EXPIRED','CONVERSATION_CHANGED','DELIVERY_AUTHORITY_CHANGED','SOURCE_EXPIRED'));
