/** Stable codes are preserved in details; labels explain the operation to readers. */
export const stageLabels: Record<string, string> = {
  ingress: "observability.messageIntake",
  wake: "observability.wakeScheduling",
  context: "observability.contextRetrieval",
  model: "observability.modelInvocation",
  action: "observability.agentAction",
  sticker: "observability.stickerSelection",
  delivery: "observability.messageDelivery",
  run: "observability.agentRun",
  maintenance: "observability.backgroundMaintenance",
};
export const statusLabels: Record<string, string> = {
  observed: "observability.observed",
  scheduled: "observability.scheduled",
  deferred: "observability.deferred",
  skipped: "observability.skipped",
  started: "observability.inProgress",
  completed: "observability.completed",
  no_output: "observability.noResponseThisTime",
  failed: "observability.processingFailed",
  cancelled: "observability.cancelled",
  unknown: "observability.resultUnconfirmed",
};
export const channelLabels: Record<string, string> = {
  web: "observability.webChat",
  onebot11: "OneBot",
  memory: "observability.memoryTask",
  knowledge: "observability.knowledgeTask",
  system: "observability.systemTask",
};
export const detailLabels: Record<string, string> = {
  requestedModel: "observability.requestedModel",
  modelResolved: "observability.actualModelConfirmed",
  model: "observability.model",
  phase: "observability.runPhase",
  durationMs: "observability.durationMs",
  attempt: "observability.attempt",
  target: "observability.recipient",
  selectedCount: "observability.selectedCount",
  candidateCount: "observability.candidateCount",
  reason: "observability.reason",
  readyAt: "observability.scheduledProcessingTime",
  throughSeq: "observability.processedThroughSequence",
  retryAt: "observability.nextAttemptAt",
};
export const taskLabels: Record<string, string> = {
  "web.main": "observability.webMainAgent",
  "onebot.main": "observability.onebotMainAgent",
  "memory.select": "observability.memorySelection",
  "memory.organize": "observability.memoryOrganising",
  "memory.consolidate": "observability.memoryOrganising",
  "memory.suppression": "observability.memorySuppressionEvaluation",
  "knowledge.select": "observability.knowledgeSelection",
  "knowledge.organize": "observability.knowledgeOrganization",
  "context.compress.events": "observability.contextCompression",
  "onebot.sticker.select": "observability.stickerSelection",
  "onebot.initiative.evaluate": "observability.initiativeEvaluation",
};
export const triggerLabels: Record<string, string> = {
  direct_reply: "observability.directReplies",
  follow_up: "observability.ongoingConversation",
  chiming_in: "observability.chimingIn",
  idle_topic: "observability.openingAQuietRoom",
  web_request: "observability.webRequest",
};
export const operationLabels: Record<string, string> = {
  "conversation.activate": "observability.conversationActivation",
  "agent.output": "observability.replyPreparation",
  "agent.context": "observability.contextRetrieval",
  "agent.checkpoint": "observability.agentCheckpoint",
  "agent.commit": "observability.replyCommit",
  "bot.ingress": "observability.messageIntake",
  "bot.ingress.media": "observability.mediaUnderstandingIntake",
  "bot.wake.offer": "observability.wakeOpportunityRegistration",
  "bot.wake.activate": "observability.wakeExecution",
  "bot.wake.recover": "observability.wakeLeaseRecovery",
  "bot.wake.recovery": "observability.wakeRecordRecovery",
  "bot.host.feedback": "observability.agentReconsiderationFeedback",
  "bot.delivery": "observability.messageDelivery",
  "bot.delivery.part": "observability.partDelivery",
  "memory.recover": "observability.memoryTaskRecovery",
  "memory.claim": "observability.memoryTaskClaim",
  "memory.job": "observability.memoryMaintenance",
  "memory.load": "observability.memorySourceReading",
  "memory.publish": "observability.memoryResultPublication",
  "knowledge.recover": "observability.knowledgeTaskRecovery",
  "knowledge.invalidate": "observability.knowledgeTaskInvalidation",
  "knowledge.wait": "observability.knowledgeTaskWaiting",
  "knowledge.job": "observability.knowledgeMaintenance",
  "knowledge.load": "observability.knowledgeSourceReading",
  "knowledge.publish": "observability.knowledgeResultPublication",
  "agent.run": "observability.agentRun",
  "agent.model": "observability.modelInvocation",
  "context.read": "observability.contextRetrieval",
  "agent.action": "observability.agentAction",
  "onebot.ingress": "observability.messageIntake",
  "wake.scheduled": "observability.wakeScheduled",
  "wake.activate": "observability.wakeExecution",
  "sticker.selected": "observability.stickerSelection",
  "delivery.send": "observability.messageDelivery",
  "memory.maintain": "observability.memoryMaintenance",
  "knowledge.maintain": "observability.knowledgeMaintenance",
};
export const reasonLabels: Record<string, string> = {
  TRIGGER_DISABLED: "observability.thisTriggerIsDisabled",
  WINDOW_NOT_READY: "observability.theProcessingWindowHasNotStarted",
  PROCESS_INTERRUPTED: "observability.processInterruptedOutcomeNeedsConfirmation",
  OPERATION_FAILED: "observability.operationDidNotCompleteInspectRelatedSteps",
};
