/** Stable codes are preserved in details; labels explain the operation to readers. */
export const stageLabels: Record<string, string> = {
  ingress: "消息接入",
  wake: "唤醒调度",
  context: "上下文读取",
  model: "模型调用",
  action: "Agent 行动",
  sticker: "表情选择",
  delivery: "消息投递",
  run: "Agent 运行",
  maintenance: "后台维护",
};
export const statusLabels: Record<string, string> = {
  observed: "已观察",
  scheduled: "已排期",
  deferred: "延后处理",
  skipped: "本次跳过",
  started: "进行中",
  completed: "已完成",
  no_output: "本次未发言",
  failed: "处理失败",
  cancelled: "已取消",
  unknown: "结果待确认",
};
export const channelLabels: Record<string, string> = {
  web: "网页对话",
  onebot11: "OneBot",
  memory: "记忆任务",
  knowledge: "知识任务",
  system: "系统任务",
};
export const detailLabels: Record<string, string> = {
  requestedModel: "请求模型",
  modelResolved: "已确认实际模型",
  model: "模型",
  phase: "运行阶段",
  durationMs: "耗时（毫秒）",
  attempt: "尝试次数",
  target: "回应对象",
  selectedCount: "已选数量",
  candidateCount: "候选数量",
  reason: "原因",
  readyAt: "计划处理时间",
  throughSeq: "处理至事件序号",
  retryAt: "下次尝试时间",
};
export const taskLabels: Record<string, string> = {
  "web.main": "网页主 Agent",
  "onebot.main": "OneBot 主 Agent",
  "memory.select": "记忆筛选",
  "memory.organize": "记忆整理",
  "memory.consolidate": "记忆整理",
  "memory.suppression": "记忆抑制判断",
  "knowledge.select": "知识筛选",
  "knowledge.organize": "知识整理",
  "context.compress.events": "上下文压缩",
  "onebot.sticker.select": "表情选择",
  "onebot.initiative.evaluate": "主动发言判断",
};
export const triggerLabels: Record<string, string> = {
  direct_reply: "直接回应",
  follow_up: "连续交谈",
  chiming_in: "自主接话",
  idle_topic: "冷场发起",
  web_request: "网页请求",
};
export const operationLabels: Record<string, string> = {
  "conversation.activate": "会话激活",
  "agent.output": "回复准备",
  "agent.context": "上下文读取",
  "agent.checkpoint": "Agent 检查点",
  "agent.commit": "回复提交",
  "bot.ingress": "消息接入",
  "bot.ingress.media": "媒体理解接入",
  "bot.wake.offer": "唤醒机会登记",
  "bot.wake.activate": "唤醒执行",
  "bot.wake.recover": "唤醒租约恢复",
  "bot.wake.recovery": "唤醒记录恢复",
  "bot.host.feedback": "Agent 复核反馈",
  "bot.delivery": "消息投递",
  "bot.delivery.part": "分段投递",
  "memory.recover": "记忆任务恢复",
  "memory.claim": "记忆任务领取",
  "memory.job": "记忆维护",
  "memory.load": "记忆来源读取",
  "memory.publish": "记忆结果入库",
  "knowledge.recover": "知识任务恢复",
  "knowledge.invalidate": "知识任务失效",
  "knowledge.wait": "知识任务等待",
  "knowledge.job": "知识维护",
  "knowledge.load": "知识来源读取",
  "knowledge.publish": "知识结果入库",
  "agent.run": "Agent 运行",
  "agent.model": "模型调用",
  "context.read": "上下文读取",
  "agent.action": "Agent 行动",
  "onebot.ingress": "消息接入",
  "wake.scheduled": "唤醒排期",
  "wake.activate": "唤醒执行",
  "sticker.selected": "表情选择",
  "delivery.send": "消息投递",
  "memory.maintain": "记忆维护",
  "knowledge.maintain": "知识维护",
};
export const reasonLabels: Record<string, string> = {
  TRIGGER_DISABLED: "该触发方式已关闭",
  WINDOW_NOT_READY: "尚未到处理窗口",
  PROCESS_INTERRUPTED: "进程中断，结果待核对",
  OPERATION_FAILED: "操作未完成，查看关联步骤",
};
